imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @ADMReportsBundle/Resources/config/admin.xml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        owner: %app_owner%
        licence: %app_licence%


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['ADMCoreBundle', 'FOSUserBundle', 'ADMUserBundle','ADMReportsBundle','ADMLeafletBundle','SonataAdminBundle','SonataUserBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  hugo.lehoux
    password:  sqfs?892

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ADM\UserBundle\Entity\User
    group:
        group_class: ADM\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address: hugo.lehoux@gmail.com
        sender_name: Hugo_Lehoux

# SONATA User Bundle
sonata_user:
    security_acl: true
    manager_type: orm
    class:
        user: ADM\UserBundle\Entity\User
        group: ADM\UserBundle\Entity\Group
    impersonating:
        route: adm_core_home
    admin:
        user:
            class: ADM\UserBundle\Admin\UserAdmin
            controller: SonataAdminBundle:CRUD
            translation: SonataUserBundle

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.rss: ~
        sonata.admin.block.search_result: ~
        sonata.user.block.menu: ~

sonata_admin:
    title:      Atlas
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Mini Calendrier configuration
sc_datetimepicker:
    picker: ~

fos_js_routing:
    routes_to_expose: [ adm_add_new_keyword ]

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    theme:
        simple:
            skin: "light"
            plugins: "paste, autoresize, table, autolink, advlist, contextmenu, link, image, responsivefilemanager"
            menubar: false
            content_css : "asset[bundles/admcore/css/bootstrap.min.css]"
            toolbar: "formatselect bold italic  bullist numlist link unlink image media inserttable undo redo "
            autoresize_max_height: 500
            contextmenu: "formatselect bold italic link unlink image media inserttable cell row column deletetable"
            relative_urls: false
            convert_urls : false
            remove_script_host : false
            external_filemanager_path: "/atlas/web/filemanager/"
            filemanager_title: "File Manager"
    external_plugins:
        filemanager:
            url: "/atlas/web/filemanager/plugin.min.js"

