# ADMReportsbundle
adm_reports:
    resource: "@ADMReportsBundle/Resources/config/routing.yml"
    prefix:   /rapport
    options:
        expose: true

# ADMReportsbundle
adm_organizations:
    resource: "@ADMReportsBundle/Resources/config/routingOrganization.yml"
    prefix:   /organisation
    options:
        expose: true

# ADMCorebundle
adm_core:
    resource: "@ADMCoreBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

# ADMLeafletBundle
adm_leaflet:
    resource: "@ADMLeafletBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

# ADMUserBundle
adm_user:
    resource: "@ADMUserBundle/Resources/config/routing.yml"
    prefix:   /

# FOS Js Routing Bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Sonata User Bundle
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

# Sonata Admin bundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

sonata_user_impersonating:
    pattern:  /
    defaults: { _controller: SonataPageBundle:Page:catchAll }