adm_report_create:
    path:     /ajouter
    defaults: { _controller: ADMReportsBundle:Report:create }

adm_report_read:
    path:     /{slug}
    defaults: { _controller: ADMReportsBundle:Report:read }

