adm_report_create:
    path:     /ajouter
    defaults: { _controller: ADMReportsBundle:Report:create }

adm_report_read:
    path:     /{slug}
    defaults: { _controller: ADMReportsBundle:Report:read }

adm_report_update:
    path:     /{slug}/editer
    defaults: { _controller: ADMReportsBundle:Report:update }

adm_keyword_create:
    path:     /tag/ajouter
    defaults: { _controller: ADMReportsBundle:Keyword:create }

adm_list_report_by_keyword:
    path:     /tag/{label}
    defaults: { _controller: ADMReportsBundle:Report:listReportsByKeyword }
