adm_report_create:
    path:     /ajouter
    defaults: { _controller: ADMReportsBundle:Report:create }

adm_add_new_keyword:
    path:     /add/keyword
    defaults: { _controller: ADMReportsBundle:Report:addNewKeyword }


adm_report_read:
    path:     /{slug}
    defaults: { _controller: ADMReportsBundle:Report:read }

adm_report_update:
    path:     /edit/{slug}
    defaults: { _controller: ADMReportsBundle:Report:update }


