homepage:
    path:     /
    defaults: { _controller: ADMUserBundle:Default:index }

reset_passwd:
    path:     /resetting/request
    defaults: { _controller: ADMUserBundle:ResettingADM:request }

adm_user_resetting_send_email:
    path:     /resetting/send-email
    defaults: { _controller: ADMUserBundle:ResettingADM:sendEmail }

new_passwd:
    path:     /resetting/reset/{token}
    defaults: { _controller: ADMUserBundle:ResettingADM:reset }

adm_user_check_email:
    path:     /resetting/send-email/success
    defaults: { _controller: ADMUserBundle:ResettingADM:checkEmail }