<?php

namespace ADM\ReportsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use ADM\ReportsBundle\Entity\Keyword;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    public function getReportsWithKeyword(array $keywordName)
    {
        $qb = $this
        ->createQueryBuilder('r')
        ->leftJoin('r.keywords', 'k')
        ->addSelect('k');

        $qb->where($qb->expr()->in('k.label', $keywordName));

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
